version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run prod
    environment:
      - PORT=4000
  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
